export const APP_LABELS_EN = {
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ADDRESS: 'Address',
    POSTCODE:'Post Code',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    MOBILE_NUMBER: 'Mobile Number',
    FORGOT_PASSWORD: 'Forgot Password?',
    ENTER__QR_CODE: 'Or Enter QR Code',
    EMAIL_LABEL2: 'Enter your user account\'s verified email address and we will send you a password reset link 請輸入您帳戶的已驗證的電郵地址，我們將向您發送密碼重置鏈結',
    BACK_2_LOGIN: 'Go Back to Login 返回登入',
    INFO_TEXT1: 'Please ensure email address is valid as winners will be contacted primarily via email.',
    INFO_TEXT2: 'Winners will be contacted both via email and SMS if they' +
    ' have provided mobile number in this form.',
    ASK_PERMISSION_AFTER_SCAN: 'You win! 你贏了',
    SKIP: 'Skip 略過',
    CONTINUE: 'Continue 繼續',
    ACTION_NOT_SUPPORTED: 'Action Not Supported',
    QR_SCANNER_INVALID_HEADER: 'QR Scanner is not supported on IOS Chrome browser',
    QR_SCANNER_INVALID_LABEL: 'Please Enter QR Code manually OR Open App on Safari browser',
    CLOSE: 'Close'
};

export const APP_LABELS_CH = {
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ADDRESS: 'Address',
    POSTCODE:'郵政編碼',
    EMAIL: 'Email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    MOBILE_NUMBER: 'Mobile Number',
    FORGOT_PASSWORD: 'Forgot Password?',
    ENTER__QR_CODE: 'Or Enter QR Code',
    EMAIL_LABEL2: 'Enter your user account\'s verified email address and we will send you a password reset link',
    BACK_2_LOGIN: 'Go Back to Login 返回登入',
    INFO_TEXT1: ' 勝出者將會收到電郵通知，請確保電郵地址正確',
    INFO_TEXT2: '勝出者如有填寫手機號碼，屆時將會收到電郵及短信通知得獎。',
    ASK_PERMISSION_AFTER_SCAN: 'You win! 你贏了',
    SKIP: 'Skip 略過',
    CONTINUE: 'Continue 繼續',
    ACTION_NOT_SUPPORTED: 'Action Not Supported',
    QR_SCANNER_INVALID_HEADER: 'QR Scanner is not supported on IOS Chrome browser',
    QR_SCANNER_INVALID_LABEL: 'Please Enter QR Code manually OR Open App on Safari browser',
    CLOSE: 'Close'
};

export const APP_LABELS_EN_CH = {
    FIRST_NAME: 'First Name 名字',
    LAST_NAME: 'Last Name 姓氏',
    ADDRESS: 'Address 住址',
    POSTCODE:'Postal Code 郵政編碼',
    EMAIL: 'Email 電郵',
    PASSWORD: 'Password 密碼',
    CONFIRM_PASSWORD: 'Confirm Password 確認密碼',
    MOBILE_NUMBER: 'Mobile No 手機號碼',
    FORGOT_PASSWORD: 'Forgot Password? 忘記密碼?',
    ENTER__QR_CODE: 'Or Enter Code 或輸入序號',
    EMAIL_LABEL2: 'Enter your user account\'s verified email address and we will send you a password reset link 請輸入您帳戶的已驗證的電郵地址，我們將向您發送密碼重置鏈結',
    BACK_2_LOGIN: 'Go Back to Login',
    INFO_TEXT1: 'Please ensure email address is valid as winners will be contacted primarily via email. 勝出者將會收到電郵通知，請確保電郵地址正確',
    INFO_TEXT2: 'Winners will be contacted both via email and SMS if they' +
    ' have provided mobile number in this form. 勝出者如有填寫手機號碼，屆時將會收到電郵及短信通知得獎。',
    ASK_PERMISSION_AFTER_SCAN: 'You win! 你贏了',
    SKIP: 'Skip 略過',
    CONTINUE: 'Continue 繼續',
    ACTION_NOT_SUPPORTED: 'Action Not Supported',
    QR_SCANNER_INVALID_HEADER: 'Error 掃描錯誤',
    QR_SCANNER_INVALID_LABEL: 'Unable to read QR code. Please try scanning again or manually enter the printed code 無法識別二維碼，請重新掃二維碼或自行輸入序號',
    CLOSE: 'Close'
};

export enum APP_LABELS {
    FIRST_NAME = 'FIRST_NAME',
    LAST_NAME = 'LAST_NAME',
    ADDRESS = 'ADDRESS',
    POSTCODE='POSTCODE',
    EMAIL = 'EMAIL',
    PASSWORD = 'PASSWORD',
    CONFIRM_PASSWORD = 'CONFIRM_PASSWORD',
    MOBILE_NUMBER = 'MOBILE_NUMBER',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    ENTER__QR_CODE = 'ENTER__QR_CODE',
    EMAIL_LABEL2 = 'EMAIL_LABEL2',
    BACK_2_LOGIN = 'BACK_2_LOGIN',
    INFO_TEXT1 = 'INFO_TEXT1',
    INFO_TEXT2 = 'INFO_TEXT2',
    ASK_PERMISSION_AFTER_SCAN = 'ASK_PERMISSION_AFTER_SCAN',
    CONTINUE = 'CONTINUE',
    SKIP = 'SKIP',
    ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED',
    QR_SCANNER_INVALID_LABEL = 'QR_SCANNER_INVALID_LABEL',
    QR_SCANNER_INVALID_HEADER = 'QR_SCANNER_INVALID_HEADER',
    CLOSE = 'CLOSE'
}
